# Generated by Django 4.2.1 on 2025-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Вместимость')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
        ),
    ]
