# Generated by Django 4.2.1 on 2025-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало занятия')),
                ('end_time', models.DateTimeField(verbose_name='Окончание занятия')),
            ],
        ),
    ]
