# Generated by Django 4.2.1 on 2025-07-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('gym_room', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='gym_room.gymroom', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='users.trainerprofile', verbose_name='Тренер'),
        ),
    ]
